apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress-queue-headless-service
  name: ingress-queue-headless-service
spec:
  clusterIP: None
  ports:
  - port: 5672
  selector:
    app: ingress-queue
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-queue-service
spec:
  selector:
    app: ingress-queue
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672